const EFFECTIVE_DATE = 'April 25, 2026';

export default function TermsModal({ onClose }: { onClose: () => void }) {
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"
      onClick={onClose}
    >
      <div
        className="relative max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-xl border border-slate-700 bg-slate-900 p-8 text-slate-300 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <button
          onClick={onClose}
          className="absolute right-4 top-4 text-slate-500 hover:text-slate-200"
        >
          ✕
        </button>

        <h1 className="mb-1 font-display text-2xl font-semibold text-slate-100">Terms of Service</h1>
        <p className="mb-6 text-xs text-slate-500">Effective Date: {EFFECTIVE_DATE}</p>

        <Section title="1. Acceptance of Terms">
          By accessing or using SheldonMind ("the Service"), you agree to be bound by these Terms of
          Service. If you do not agree to these terms, please do not use the Service.
        </Section>

        <Section title="2. Description of Service">
          SheldonMind is an AI-powered assistant platform that allows users to interact with multiple
          large language model (LLM) providers, generate images and videos, manage conversation
          history, and access a community prompt library. The Service requires account registration
          and operates on a credit-based billing system.
        </Section>

        <Section title="3. Account Registration">
          <ul className="list-disc space-y-1 pl-5">
            <li>You must sign in via Google OAuth to use the Service.</li>
            <li>You are responsible for maintaining the confidentiality of your account.</li>
            <li>You must be at least 13 years of age (or the minimum age of digital consent in your jurisdiction) to use the Service.</li>
            <li>You agree to provide accurate information and keep it up to date.</li>
          </ul>
        </Section>

        <Section title="4. Credits & Billing">
          <ul className="list-disc space-y-1 pl-5">
            <li>The Service operates on a credit system. Credits are consumed when you send messages, generate images, or generate videos.</li>
            <li>Credits can be purchased via top-up or subscription plans processed through our payment provider (Lemon Squeezy).</li>
            <li>All purchases are final and non-refundable unless required by applicable law.</li>
            <li>SheldonMind reserves the right to change credit pricing with reasonable notice.</li>
          </ul>
        </Section>

        <Section title="5. Acceptable Use">
          You agree NOT to use the Service to:
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Generate content that is illegal, harmful, threatening, abusive, defamatory, or violates any third-party rights.</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the API in ways that violate provider terms (OpenAI, Anthropic, Google, etc.).</li>
            <li>Circumvent usage limits, share accounts, or sell access to the Service.</li>
            <li>Generate spam, misinformation, or content intended to deceive others.</li>
          </ul>
        </Section>

        <Section title="6. AI-Generated Content">
          <ul className="list-disc space-y-1 pl-5">
            <li>AI outputs are generated by third-party LLM providers and may be inaccurate, incomplete, or inappropriate. Do not rely on them for medical, legal, or financial decisions.</li>
            <li>You retain ownership of prompts you submit. You grant SheldonMind a limited license to process your prompts to deliver the Service.</li>
            <li>Public generations and prompts shared to the community gallery may be viewed and forked by other users.</li>
          </ul>
        </Section>

        <Section title="7. Intellectual Property">
          All platform software, UI, branding, and non-user-generated content are owned by
          SheldonMind. You may not copy, distribute, or create derivative works without written
          permission.
        </Section>

        <Section title="8. Third-Party Services">
          The Service integrates with third-party providers (OpenAI, Anthropic, Google AI, Mistral,
          Groq, Lemon Squeezy, AWS S3, etc.). Your use of those services is also governed by their
          respective terms of service.
        </Section>

        <Section title="9. Disclaimer of Warranties">
          The Service is provided "as is" without warranties of any kind. SheldonMind does not
          guarantee uninterrupted availability, accuracy of AI outputs, or fitness for a particular
          purpose.
        </Section>

        <Section title="10. Limitation of Liability">
          To the maximum extent permitted by law, SheldonMind shall not be liable for any indirect,
          incidental, special, or consequential damages arising from your use of the Service,
          including loss of data or profits.
        </Section>

        <Section title="11. Termination">
          We reserve the right to suspend or terminate accounts that violate these Terms, misuse the
          Service, or engage in fraudulent activity, without prior notice.
        </Section>

        <Section title="12. Changes to Terms">
          We may update these Terms from time to time. Continued use of the Service after changes
          are posted constitutes acceptance of the new terms.
        </Section>

        <Section title="13. Contact">
          For questions about these Terms, contact us at{' '}
          <a href="mailto:support@sheldonmind.com" className="text-blue-400 hover:underline">
            support@sheldonmind.com
          </a>
          .
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-5">
      <h2 className="mb-2 text-sm font-semibold uppercase tracking-wide text-slate-100">{title}</h2>
      <div className="text-sm leading-relaxed text-slate-400">{children}</div>
    </div>
  );
}
